sudo : required
services: 
    - docker

before_install: 
    - docker build -t uyoko/docker=react -f Dockerfile.dev .

script:
    # - docker run uyoko/docker=react npm run test -- --coverage        # not working anymore
    - docker run -e CI=true uyoko/docker=react npm run test