version: '3'
services: 
    web:
        # build: .
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules #Ignore mapping this folder inside container
            - .:/app

    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev        
        volumes: 
            - /app/node_modules #Ignore mapping this folder inside container
            - .:/app 
        command: ["npm", "run", "test"]